--Write a query to retrieve the full names of all customers who live in Mexico.
select 
	concat(first_name,' ',last_name) as full_name,customer_country
from customers
where customer_country = 'Mexico'

--How many stores does Maven Market have in each country?
select
	store_country,count(*) as no_of_stores
from stores 
group by store_country

--List all product names that are both low fat and recyclable.
select
	product_name,low_fat,recyclable
from products
where low_fat = 1 and recyclable = 1

--Show all unique sales_region names available in the Regions table
select 
	distinct sales_region
from regions

--Retrieve all columns from the Transactions table for a specific customer (customer_id = 3449)
select 
	*
from transactions
where customer_id = 3449


--calculate the total revenue generated by each product_brand
select
	product_brand,
	sum(quantity * product_retail_price) as total
from transactions t
join products p on t.product_id = p.product_id 
group by product_brand
order by total desc


--find the top 5 customers (name and total quantity purchased) who have bought the most items across all transactions.
select 
	c.customer_id,first_name,last_name,
	sum(quantity) as total_items_purchased
from customers c
join transactions t on c.customer_id = t.customer_id
group by c.customer_id,first_name,last_name
order by total_items_purchased desc
limit 5; 


--Join Transactions, Stores, and Regions to find the total quantity of items sold in the 'North West' sales region.
select
	sales_region,
	sum(quantity) as total_quantity
from transactions t 
join stores s on t.store_id = s.store_id
join regions r on s.region_id = r.region_id
where sales_region = 'North West'
group by sales_region;


--Count the total number of returns for each product_id, but only include products that have been returned more than 5 times.
SELECT
	r.product_id, p.product_name,
	count(*) as times_returned
FROM returns r
join products p on r.product_id = p.product_id
group by r.product_id, p.product_name
having count(*) > 5
order by times_returned desc


--Calculate the Total Profit (Total Revenue - Total Cost) for every month in 1998.
select
	extract (month from transaction_date) as month_number,
	to_char(date,'Month') as month_name,
	ROUND(SUM(quantity * product_retail_price), 2) as total_revenue,
    ROUND(SUM(quantity * product_cost), 2) as total_cost,
    ROUND(SUM(quantity * (product_retail_price - product_cost)), 2) AS total_profit
from products p
join transactions t on p.product_id = t.product_id
join calender c on t.transaction_date = c.date
where extract (year from transaction_date) = 1998
group by month_number,month_name
order by month_number


-- For every product, calculate its Return Rate. Formula: (Total Quantity Returned / Total Quantity Sold) * 100.
SELECT
	r.product_id,
	sum(t.quantity) as total_sales,
	sum(r.quantity) as total_returns,
	round(((sum(r.quantity) / sum(t.quantity))*100),2) as return_rate
FROM returns r
join transactions t on r.product_id = t.product_id
group by r.product_id
order by return_rate desc

--Categorize customers into three groups based on their yearly_income: 'Entry', 'Mid-Level', and 'Executive'. Count how many customers fall into each category.
SELECT 
	yearly_income,
	count(*) as no_of_customers
FROM customers
group by yearly_income
order by 
	case yearly_income
		when '$10K - $30K' then 1
		when '$30K - $50K' then 2
		when '$50K - $70K' then 3
		when '$70K - $90K' then 4
		when '$90K - $110K' then 5
		when '$110K - $130K' then 6
		when '$130K - $150K' then 7
		when '$150K +' then 8 
	end

--Rank the sales_district within each sales_region based on their total sales quantity using a Window Function
select
	sales_region,
	sales_district,
	sum(quantity) as total_quantity,
	row_number() over(partition by sales_region order by sum(quantity) desc) as rn
from transactions t
join stores s on t.store_id = s.store_id
join regions r on s.region_id = r.region_id
group by sales_region,sales_district

--Find customers who made a purchase in 1997 but have zero transactions recorded in 1998
SELECT 
    c.customer_id, 
    c.first_name, 
    c.last_name,
    c.customer_city,
    c.customer_country
FROM customers c
WHERE 
    c.customer_id IN (
        SELECT customer_id 
        FROM Transactions 
        WHERE transaction_date BETWEEN '1997-01-01' AND '1997-12-31'
    )
    AND c.customer_id NOT IN (
        SELECT customer_id 
        FROM Transactions 
        WHERE transaction_date BETWEEN '1998-01-01' AND '1998-12-31'
    )
ORDER BY c.customer_id;


